/*******************************************************/
// game.js
// Main Game Function
// Alexis Hood
//USAGE OF MATERIAL:
//All files under /image folder generated by ChatGPT, in line with https://openai.com/policies/
//All other files and content used in the program were created by me.
/*******************************************************/

//Initialise all global variables and consts
const CNV_WIDTH = 700;
const CNV_HEIGHT = 700;
const MAX_LIVES = 10;
let lives = MAX_LIVES;
let timerScore = 0;
let gameMode = 1; //Start Screen
let twoPlayer; //Boolean whether the game is Two Player or One Player

//Setup Button Animations
let buttonAnimation = "small"; //2P Game Button
let buttonAnimation1P = "small"; //1P Game Button
let buttonAnimationRestart = "small"; //Restart Game Button


/*******************************************************/
// preload()
/*******************************************************/
function preload() {
    //Preloads all of the required image files
    console.log("Preload");
    player1img = loadImage('images/player1.png');
    player2img = loadImage('images/player2.png');
    greenButton = loadImage('images/greenButton.png');
    blueButton = loadImage('images/blueButton.png');
    redButton = loadImage('images/redButton.png');
    restartIMG = loadImage('images/restartIcon.png');
}


/*******************************************************/
// setup()
/*******************************************************/
function setup() {
    let cnv = createCanvas(CNV_WIDTH, CNV_HEIGHT + 50);
    cnv.position((windowWidth / 2) - (CNV_WIDTH / 2), (windowHeight / 2) - (CNV_HEIGHT / 2)); //Centers canvas in screen
    frameRate(60);

    //Start Screen Text 1
    gameName1 = new Sprite(-100, 100, 1200, 300, 'k');
    gameName1.image = (blueButton);
    gameName1.scale = 0.25;
    gameName1.text = 'JET';
    gameName1.textColor = "#eef0fd";
    gameName1.textSize = 30;

    //Start Screen Text 2
    gameName2 = new Sprite(700, 200, 1200, 300, 'k');
    gameName2.image = (redButton);
    gameName2.scale = 0.25;
    gameName2.text = 'FIGHTERS';
    gameName2.textColor = "#fdeeee";
    gameName2.textSize = 30;

    //1 Player Start Button
    startButton1Player = new Sprite(CNV_WIDTH / 2, 300, 1200, 300, 'k');
    startButton1Player.image = (greenButton);
    startButton1Player.scale = 0.25;
    startButton1Player.text = "1 PLAYER START \u25B6";
    startButton1Player.textColor = "#4b965b";
    startButton1Player.textSize = 30;

    //2 Player Start Button
    startButton = new Sprite(CNV_WIDTH / 2, 400, 1200, 300, 'k');
    startButton.image = (greenButton);
    startButton.scale = 0.25;
    startButton.text = "2 PLAYER START \u25B6";
    startButton.textColor = "#4b965b";
    startButton.textSize = 30;

    //Game Instructions
    instructions = new Sprite(CNV_WIDTH / 2, 500, 1600, 1000);
    instructions.color = "#caf8cd";
    instructions.scale = 0.25;
    instructions.text = 'Instructions: \n Player 1 (Red): Left + Right Arrow Keys \n Player 1 Space to Shoot \n Player 2 (Blue): A + D Keys \n\n The aim is for Player 1 (Red) \n to shoot Player 2 (Blue) until \nthey lose all their lives ';
    instructions.textColor = "#4b965b";
    instructions.textSize = 20;
}

/*******************************************************/
// gameSetup()
/*******************************************************/
function gameSetup() {
    //Resets Canvas
    allSprites.remove();

    //Creates Top Info Bar, Lives display
    livesBar = new Sprite(CNV_WIDTH / 4, 25, CNV_WIDTH / 2, 50, 'n');
    livesBar.color = 'black';
    livesBar.layer = 10;
    livesBar.strokeWeight = 0;

    //Creates Top Info Bar, Timer display
    timerBar = new Sprite((CNV_WIDTH / 4) + (CNV_WIDTH / 2), 25, CNV_WIDTH / 2, 50, 'n');
    timerBar.color = 'black';
    timerBar.layer = 10;
    timerBar.text = "0";
    timerBar.strokeWeight = 0;

    //Creates Top Info Bar, Restart Icon + Button
    restartIcon = new Sprite((CNV_WIDTH - 30), 30, 500, 500, 's');
    restartIcon.image = (restartIMG);
    restartIcon.scale = 0.06;
    restartIcon.layer = 11;
    restartIcon.overlaps(allSprites); //No sprites can collide with the icon

    //Creates Player 1 + Player 2, Projectile Group
    createPlayer1();
    createPlayer2();
    projectileGroup = new Group();

    //Sets game start frame for timer, Sets lives to max lives
    startFrame = frameCount / 60;
    lives = MAX_LIVES;
}

/*******************************************************/
// gameOverSetup()
/*******************************************************/
function gameOverSetup(_isAlive) {
    //Resets Canvas + Button animations
    allSprites.remove();
    buttonAnimation = "small";
    buttonAnimation1P = "small"
    buttonAnimationRestart = "small"

    //If Player 1 dies (Player 1 + 2 collided) when game ends, then show collision version of End Screen 
    //If Player 1 is alive when game ends, then show P1 Wins + Score version of End Screen
    if (_isAlive == "dead") {
        //End Screen Text 1 With Score With message you lose
        deadMessage = new Sprite((CNV_WIDTH / 2) - 100, 100, 1200, 300, 'n');
        deadMessage.image = (redButton);
        deadMessage.scale = 0.25;
        deadMessage.text = 'Player 1 Loses! Score: ' + timerScore;
        deadMessage.textColor = "#fdeeee";
        deadMessage.textSize = 25;

        //End Screen Text 2 With Score With message you crashed
        deadMessage2 = new Sprite((CNV_WIDTH / 2), 200, 1200, 300, 'n');
        deadMessage2.image = (redButton);
        deadMessage2.scale = 0.25;
        deadMessage2.text = 'You Crashed';
        deadMessage2.textColor = "#fdeeee";
        deadMessage2.textSize = 30;

        //Restart Button
        restartButton = new Sprite((CNV_WIDTH / 2) - 100, (CNV_HEIGHT / 2), 1200, 300, 'k');
        restartButton.image = (greenButton);
        restartButton.scale = 0.25;
        restartButton.text = "REPLAY \u25B6";
        restartButton.textColor = "#4b965b";
        restartButton.textSize = 30;
    } else if (_isAlive == "alive") {
        //End Screen Text 1
        aliveMessage = new Sprite((CNV_WIDTH / 2) - 100, 100, 1200, 300, 'n');
        aliveMessage.image = (redButton);
        aliveMessage.scale = 0.25;
        aliveMessage.text = 'It took you:';
        aliveMessage.textColor = "#fdeeee";
        aliveMessage.textSize = 30;

        //End Screen Text 2 with score
        aliveMessage2 = new Sprite((CNV_WIDTH / 2), 200, 1200, 300, 'n');
        aliveMessage2.image = (redButton);
        aliveMessage2.scale = 0.25;
        aliveMessage2.text = timerScore + ' secs';
        aliveMessage2.textColor = "#fdeeee";
        aliveMessage2.textSize = 30;

        //End Screen Text 3
        aliveMessage3 = new Sprite((CNV_WIDTH / 2) + 100, 300, 1200, 300, 'n');
        aliveMessage3.image = (redButton);
        aliveMessage3.scale = 0.25;
        aliveMessage3.text = 'To eliminate player 2!';
        aliveMessage3.textColor = "#fdeeee";
        aliveMessage3.textSize = 30;

        //Restart Button
        restartButton = new Sprite((CNV_WIDTH / 2) - 100, (CNV_HEIGHT / 2) + 100, 1200, 300, 'k');
        restartButton.image = (greenButton);
        restartButton.scale = 0.25;
        restartButton.text = "REPLAY \u25B6";
        restartButton.textColor = "#4b965b";
        restartButton.textSize = 30;
    }

}

/*******************************************************/
// createPlayer1()
/*******************************************************/
function createPlayer1() {
    //Creates Player 1, gives image, sets size + direction
    player1 = new Sprite(CNV_WIDTH - 100, CNV_HEIGHT - 100, 30, 30, 'd');
    player1.image = (player1img);
    player1.scale = 50 / player1img.width;
    player1.direction = -90;
    player1.rotation = 0;
    player1.collider = 'd';
    player1.w = 30;
    player1.h = 30;
    player1.layer = 5;
}


/*******************************************************/
// createPlayer2()
/*******************************************************/
function createPlayer2() {
    //Creates Player 2, gives image, sets size + direction
    player2 = new Sprite(100, 150, 30, 30, 'd');
    player2.image = (player2img);
    player2.scale = 50 / player2img.width;
    player2.direction = -90;
    player2.rotation = 0;
    player2.collider = 'd';
    player2.w = 30;
    player2.h = 30;
    player2.layer = 5;
}


/*******************************************************/
// player1Movement()
/*******************************************************/
function player1Movement() {
    player1.speed = 3;
    if (kb.pressing('arrowLeft')) {
        player1.direction = Math.floor(player1.direction - 2);
    } else if (kb.pressing('arrowRight')) {
        player1.direction = Math.floor(player1.direction + 2);
    }
    player1.rotation = player1.direction - 270;

    //Wraps the player if they go off screen
    if (player1.x < 0) {
        player1.x = CNV_WIDTH;
    } else if (player1.x > CNV_WIDTH) {
        player1.x = 0;
    } else if (player1.y < 50) {
        player1.y = CNV_HEIGHT;
    } else if (player1.y > CNV_HEIGHT) {
        player1.y = 50;
    }
}

/*******************************************************/
// player2Movement()
/*******************************************************/
function player2Movement(_isBot) {
    player2.speed = 3;
    if (_isBot) {
        if (Math.floor(player2.direction) != (Math.floor(player1.direction) - 180) && Math.floor(player1.direction) < 0) {
            player2.direction = Math.floor(player2.direction - 1);
        } else if (Math.floor(player2.direction) != (Math.floor(player1.direction) - 180) && Math.floor(player1.direction) > 0) {
            player2.direction = Math.floor(player2.direction + 1);
        }
    } else {
        if (kb.pressing('a')) {
            player2.direction = player2.direction - 2;
            player2.rotation = player2.rotation - 2;
        } else if (kb.pressing('d')) {
            player2.direction = player2.direction + 2;
            player2.rotation = player2.rotation + 2;
        }
    }

    player2.rotation = player2.direction - 270;



    //Wraps the player if they go off screen
    if (player2.x < 0) {
        player2.x = CNV_WIDTH;
    } else if (player2.x > CNV_WIDTH) {
        player2.x = 0;
    } else if (player2.y < 50) {
        player2.y = CNV_HEIGHT;
    } else if (player2.y > CNV_HEIGHT) {
        player2.y = 50;
    }
}

/*******************************************************/
// createProjectile()
/*******************************************************/
function createProjectile() {
    let projectile = new Sprite(player1.x, player1.y, 2, 4, 'd');
    projectile.direction = player1.direction;
    projectile.rotation = player1.rotation;
    projectile.speed = 8;
    projectile.color = 'black';
    projectile.layer = 2;
    projectileGroup.add(projectile);
}

/*******************************************************/
// removeProjectile()
/*******************************************************/
function removeProjectile(_projectile) {
    lives = lives - 1;
    console.log("lives: " + lives);
    for (let i = 0; i < 5; i++) {
        particle = new Sprite(_projectile.x, _projectile.y, 1, 1, 'n');
        particle.color = 'black';
        particle.direction = random(-180, 180);
        particle.rotation = particle.direction;
        particle.speed = 10;
    }
    _projectile.remove();
}

/*******************************************************/
// livesDisplay()
/*******************************************************/
function livesDisplay() {
    livesBar.text = "Lives: " + lives;
    livesBar.textColor = 'white';
    livesBar.textSize = 20;
    timerScore = Math.floor(((frameCount / 60) - startFrame));
    timerBar.text = 'Time: ' + timerScore;
    timerBar.textColor = "White";
    timerBar.textSize = 20;
}


/*******************************************************/
// gameLoop()
/*******************************************************/
function gameLoop() {

    background('white');
    player1Movement();
    if (twoPlayer) {
        player2Movement(false);
    } else {
        player2Movement(true);
    }


    if (restartIcon.mouse.pressed()) {
        console.log("Game ReStarting");
        gameSetup();
        gameMode = 2;
        return;
    }

    if (kb.pressed('space')) {
        createProjectile();
    }

    projectileGroup.forEach(sprite => {
        if (sprite.x < 0) {
            sprite.remove();
        } else if (sprite.x > CNV_WIDTH) {
            sprite.remove();
        } else if (sprite.y < 0) {
            sprite.remove();
        } else if (sprite.y > CNV_HEIGHT) {
            sprite.remove();
        }
    });

    projectileGroup.overlaps(player2, removeProjectile);
    projectileGroup.overlaps(player1);

    if (player1.collides(player2)) {
        timerScore = 0;
        gameOverSetup("dead");
        gameMode = 3;
        return;
    }
    livesDisplay();

    if (lives <= 0) {
        console.log("GAME OVER");
        gameOverSetup("alive");
        gameMode = 3;
        return;
    }


}

/*******************************************************/
// startScreen()
/*******************************************************/
function startScreen() {
    background('white');
    if (startButton.mouse.pressed()) {
        console.log("Game Starting");
        twoPlayer = true;
        gameSetup();
        gameMode = 2;
        return;
    }
    if (startButton1Player.mouse.pressed()) {
        console.log("Game Starting");
        twoPlayer = false;
        gameSetup();
        gameMode = 2;
        return;
    }
    // Name Animation
    if (gameName1.x < 100) {
        gameName1.x = gameName1.x + 4;
    }
    if (gameName2.x > 200) {
        gameName2.x = gameName2.x - 10;
    }

    if (startButton.scale < 0.28 && buttonAnimation == "small") {
        startButton.scale = startButton.scale + 0.0006;
        //Start Button - pulsating startButton
    } else if (startButton.scale > 0.25) {
        startButton.scale = startButton.scale - 0.0006;
        buttonAnimation = "big";
    } else {
        buttonAnimation = "small";
    }

    if (startButton1Player.scale < 0.28 && buttonAnimation1P == "small") {
        startButton1Player.scale = startButton1Player.scale + 0.0006;
        //Start Button - pulsating startButton
    } else if (startButton1Player.scale > 0.25) {
        startButton1Player.scale = startButton1Player.scale - 0.0006;
        buttonAnimation1P = "big";
    } else {
        buttonAnimation1P = "small";
    }
}


/*******************************************************/
// gameOver()
/*******************************************************/
function gameOver() {
    background('white');
    if (restartButton.mouse.pressed()) {
        console.log("Game Restarting");
        gameSetup();
        gameMode = 2;
        return;
    }
    // Restart Animation
    if (restartButton.scale < 0.28 && buttonAnimationRestart == "small") {
        restartButton.scale = restartButton.scale + 0.0006;
        //Start Button - pulsating startButton
    } else if (restartButton.scale > 0.25) {
        restartButton.scale = restartButton.scale - 0.0006;
        buttonAnimationRestart = "big";
    } else {
        buttonAnimationRestart = "small";
    }
}

/*******************************************************/
// draw()
/*******************************************************/
function draw() {
    if (gameMode == 1) {
        startScreen();
    } else if (gameMode == 2) {
        gameLoop();
    } else if (gameMode == 3) {
        gameOver();
    }

}


/*
TO DO:
More Comments
*/




/*******************************************************/
//  END OF game.js
/*******************************************************/